export const storeLevels = {
  // Level 1 (General retail / fashion / essentials)
  "Adidas": 1,
  "Nike": 1,
  "Lifestyle": 1,
  "Max": 1,
  "Splash": 1,
  "Trends": 1,
  "Trends Footwear": 1,
  "Centro": 1,
  "Jockey": 1,
  "Monte Carlo": 1,
  "Numero Uno": 1,
  "Go Colors": 1,
  "Mini Club": 1,
  "Bata": 1,
  "Skechers": 1,
  "Shoe Tree": 1,
  "Lenskart": 1,
  "Sports Station": 1,
  "House of Candy": 1,
  "Tents": 1,

  // Level 2 (Premium brands / electronics / lifestyle)
  "Apple": 2,
  "Victoria's Secret": 2,
  "Zara": 2,
  "Zara Kids": 2,
  "H&M": 2,
  "H&M Home": 2,
  "Charles & Keith": 2,
  "Vero Moda": 2,
  "Forever 21": 2,
  "Jack & Jones": 2,
  "GAP": 2,
  "GAP Kids": 2,
  "Muji": 2,
  "Sephora": 2,
  "Levi's": 2,
  "Pepe Jeans": 2,
  "Marks & Spencer": 2,
  "Marks & Spencer Food": 2,
  "Louis Philippe": 2,
  "Woodland": 2,
  "Reliance Digital": 2,
  "Croma": 2,
  "Future World (Apple)": 2,
  "M&S": 2,
  "Mini So": 2,
  "EVS Sports": 2,
  "Decathlon": 2,

  // Level 3 (Food court / entertainment)
  "Starbucks": 3,
  "McDonald's": 3,
  "KFC": 3,
  "PVR": 3,
  "PVR Cinemas": 3,
  "Cafe Coffee Day": 3,
  "Haldiram's": 3,
  "Taco Bell": 3,
  "Yo China": 3,
  "Brew Waves": 3,
  "Pirates of Grill": 3,
  "Chaat Bazaar": 3,
  "Bonzai Banzai": 3,
  "Taco Biryani": 3,
  "Funcity": 3,
  "Hamleys": 3,
  "Amiran Biryani": 3,
  "Burger King": 3,
  "Wok Noodles": 3,
  "Domino's": 3,
  "Subway": 3,
  "Gyro Express": 3,
  "Havmor": 3,
  "Sonbrage": 3
};